- name: EC2 creates VPC on ohio region 
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes
  become_method: sudo
  tasks:
  
# ------------------VPC CREATION STARTS HERE-------------------

    - name: create VPC with tags
      ec2_vpc_net:
        name: talant_VPC_ohio
        cidr_block: 10.0.0.0/16
        region: "{{region}}"
        tags:
          name: talant_VPC_ohio
        tenancy: default

# ------------------VPC GATHER FACTS-------------------

    - name: gather facts to get vpc_id of talant_VPC_ohio
      ec2_vpc_net_facts:
        region: "{{region}}"
        filters: 
          "tag:Name": talant_VPC_ohio
      

    - name: Display VPC facts(information)
      debug:
        var: my_vpc_info.vpcs[0].vpc_id

# ------------------PUBLIC-SUBNET-STARTS HERE-------------------
# ------------------PUBLIC-SUBNET-1-------------------

    - name: Create subnet in talant_VPC_ohio
      ec2_vpc_subnet:
        region: "{{region}}"
        az: "{{az1}}"
        state: present
        vpc_id: "{{my_vpc_info.vpcs[0].vpc_id}}"
        cidr: 10.0.1.0/24
        resource_tags:
          Name: my_public_subnet   


# ------------------PUBLIC-SUBNET-2-------------------
    - name: Create subnet in talant_VPC_ohio
      ec2_vpc_subnet:
        region: "{{region}}"
        az: "{{az2}}"
        state: present
        vpc_id: "{{my_vpc_info.vpcs[0].vpc_id}}"
        cidr: 10.0.2.0/24
        resource_tags:
          Name: my_public_subnet


# ------------------PUBLIC-SUBNET-3-------------------
    - name: Create subnet in talant_VPC_ohio
      ec2_vpc_subnet:
        region: "{{region}}"
        az: "{{az3}}"
        state: present
        vpc_id: "{{my_vpc_info.vpcs[0].vpc_id}}"
        cidr: 10.0.3.0/24
        resource_tags:
          Name: my_public_subnet
# ------------------PUBLIC-SUBNET-ENDS HERE-------------------
 

         

