- name: EC2 creates VPC on ohio region 
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes
  become_method: sudo
  tasks:
    - name: create VPC with tags
      ec2_vpc_net:
        name: talant_VPC_ohio
        cidr_block: 10.0.0.0/16
        region: "{{region}}"
        tags:
          name: talant_VPC_ohio
        tenancy: default

    - name: gather facts to get vpc_id of talant_VPC_ohio
      ec2_vpc_net_facts:
        region: "{{region}}"
        filters: 
          "tag:Name": talant_VPC_ohio
      register: my_vpc_info 

    - name: Display VPC facts(information)
      debug:
        var: my_vpc_info.vpcs[0].vpc_id
        
# Public subnets created steps 
    # - name: Create subnet in talant_VPC_ohio
    #   ec2_vpc_subnet:
    #     region: "{{region}}"
    #     state: present
    #     vpc_id: "{{my_vpc_info.vpcs[0].vpc_id}}"
    #     cidr: 10.0.1.16/24
    #     resource_tags:
    #       Name: public   

#     - name: Create subnet in talant_VPC_ohio
#       ec2_vpc_subnet:
#         region: "{{region}}"
#         state: present
#         vpc_id: "{{my_vpc_info.vpcs[0].vpc_id}}"
#         cidr: 10.0.2.16/24
#         resource_tags:
#           Name: public

#     - name: Create subnet in talant_VPC_ohio
#       ec2_vpc_subnet:
#         region: "{{region}}"
#         state: present
#         vpc_id: "{{my_vpc_info.vpcs[0].vpc_id}}"
#         cidr: 10.0.3.16/24
#         resource_tags:
#           Name: public
# # --------------------END OF PUBLIC SUBNET---------------------------------- 
     