- name: VPC gather facts
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes
  become_method: sudo
  tasks:
  #-------------------------------------------
  - name: gather facts of default VPC
    ec2_vpc_net_facts:
      region: "{{region}}"
      filters: 
        "tag:Name": "{{tag_of_VPC}}"
    register: vpc_facts

  - name: Print VPC details
    debug:
      var: vpc_facts.vpcs[0].vpc_id

  #-------------------------------------------
  - name: Subnet get id
    ec2_vpc_subnet_facts:
      region: "{{region}}"
      filters:
        vpc-id: vpc_facts.vpcs[0].vpc_id
        "tag:Name": "{{items}}"
      loop:
        - sub1
        - sub2
        - sub3
        
        
    register: subnet_facts

  - debug:
      var: subnet_facts

  


  
  
    


        