- name: VPC gather facts
  hosts: localhost
  vars:
    my_vpc_id: vpc_facts.vpcs[0].vpc_id
  connection: local
  gather_facts: false
  become: yes
  become_method: sudo
  tasks:
  #-------------------------------------------
  - name: gather facts of default VPC
    ec2_vpc_net_facts:
      region: "{{region}}"
      filters: 
        "tag:Name": "{{tag_of_VPC}}"
    register: vpc_facts.vpcs[0].vpc_id

  - name: Print VPC details
    debug:
      var: my_vpc_id

  #-------------------------------------------
  - name: Subnet get id
    ec2_vpc_subnet_facts:
      region: "{{region}}"
      filters:
        vpc-id: my_vpc_id
        
    register: subnet_facts

  - debug:
      var: subnet_facts.subnets[0].subnet_id


  


  
  
    


        