- name: VPC gather facts
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes
  become_method: sudo
  tasks:
  - name: gather facts of default VPC
    ec2_vpc_net_facts:
      region: us-east-2
#      filters: 
#        "tag:Name": Default-VPC
    register: vpc_facts
  - debug:
      var: vpc_facts

  
    


        