- name: VPC gather facts
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes
  become_method: sudo
  tasks:
  - ec2_vpc_net_facts:
      region: us-east-2
      filters:
        vpc-id: vpc-be96e0d6


        